import { HttpTypes } from "@medusajs/types"

/**
 * The gift card is the one product this demo sells that is not a grocery item
 * mirrored from Vori. Its variants carry this flag, set when the store is
 * seeded, and everything that treats a gift card differently keys on it.
 */
export const isGiftCardVariant = (
  variant?: HttpTypes.StoreProductVariant | null
): boolean => variant?.metadata?.vori_gift_card === true

export const isGiftCardProduct = (
  product?: HttpTypes.StoreProduct | null
): boolean => (product?.variants ?? []).some(isGiftCardVariant)

export const isGiftCardLineItem = (item?: {
  variant?: HttpTypes.StoreProductVariant | null
}): boolean => isGiftCardVariant(item?.variant)

/**
 * A fresh barcode for a gift card, generated by this demo rather than by Vori:
 * Vori stores the barcode the seller supplies and does not mint one. It is a
 * plain digit string, which every Code 128 reader encodes, prefixed so a card
 * is recognisable at a glance among a store's other barcodes.
 */
export const generateGiftCardBarcode = (): string => {
  const digits = new Uint8Array(12)
  if (typeof crypto !== "undefined" && crypto.getRandomValues) {
    crypto.getRandomValues(digits)
  } else {
    for (let i = 0; i < digits.length; i++) {
      digits[i] = Math.floor(Math.random() * 256)
    }
  }

  const body = Array.from(digits, (n) => String(n % 10)).join("")
  return `VGC${body}`
}
